### ISSUE TITLE
Stack?

### ISSUE THREAD

**Issue by eletroswing** [eletroswing/bacen-simulator#1]
What technologies and languages should we use?
I think of something simple, for everyone, something like go or js/ts.

**Comment by calilisantos** [comment]
To data processing i think in `python`. Depends on data volumetry we could use pandas or pyspark (for big data) python tools.

**Comment by yandevv** [comment]
> To data processing i think in `python`. Depends on data volumetry we could use pandas or pyspark (for big data) python tools.

Do you think to use separated languages? Like a server just to data processing using python, and another lang to make the backend itselfs (eg. routes to the frontend)

**Comment by eletroswing** [comment]
i was thinking about use sqlite for the project, cause its ligthweight and fast, we can make a good enviroment arround it

**Comment by eletroswing** [comment]
and about fastify + node for backend?

**Comment by yandevv** [comment]
My actual final idea is:

Backend:
- Fastify (Node)
- SQLite

Frontend (Online Documentation):
- Docusaurus

**Comment by eletroswing** [comment]
I liked this stack, any additions or changes we can open an issue mentioning to discuss.
If we use node, we can use (commitizen)[https://github.com/commitizen/cz-cli] as dev dependency for a message commit pattern

**Comment by yandevv** [comment]
I totally agree with commitizen!

**Comment by calilisantos** [comment]
> > To data processing i think in `python`. Depends on data volumetry we could use pandas or pyspark (for big data) python tools.
> 
> Do you think to use separated languages? Like a server just to data processing using python, and another lang to make the backend itselfs (eg. routes to the frontend)

Yes, thinking in the python advantage to this goal could be great
