### ISSUE TITLE
DICT - Update pix key params

### ISSUE THREAD

**Issue by eletroswing** [eletroswing/bacen-simulator#6]
> Based on doc: https://www.bcb.gov.br/content/estabilidadefinanceira/pix/API-DICT-2.0.1.html#tag/Directory/operation/updateEntry

These would not be the main parameters, but equally important in the dict simulation would be updating a pix key.
They can be found at:
- Update: https://www.bcb.gov.br/content/estabilidadefinanceira/pix/API-DICT-2.0.1.html#tag/Directory/operation/updateEntry

**Comment by yandevv** [comment]
> Somente podem ser atualizadas as **informações de conta do vínculo**, **nome** e **nome fantasia** do cliente. Outras atualizações do vínculo devem ser feitas por exclusão/inclusão do vínculo, portabilidade ou reivindicação de posse, a depender da situação.
> Restrições
>As seguintes restrições devem ser obedecidas na atualização de vínculo, de acordo com o tipo de chave:

>Chaves EVP (aleatórias) - É permitida a alteração, porém, apenas com os motivos BRANCH_TRANSFER ou RECONCILIATION.
>Demais chaves - É permitida a alteração com os motivos USER_REQUESTED, BRANCH_TRANSFER ou RECONCILIATION.

Alterações somente em:
- Informações de conta da entry
- Nome
- Nome-fantasia (caso houver)

Em chaves _EVP_ somente com reasons: **BRANCH_TRANSFER** e **RECONCILIATION**

Nas demais chaves, somente com reasons: **USER_REQUESTED**, **BRANCH_TRANSFER** e **RECONCILIATION**
